### ISSUE TITLE
How to run docker on windows

### ISSUE THREAD

**Issue by marcnoon** [EOSIO/eosio-webauthn-example-app#16]
Notice there is docs for Ubuntu and Mac.  Is there any docs for installing docker on Windows 10?

**Comment by jlamarr22** [comment]
@marcnoon https://docs.docker.com/docker-for-windows/install/

Did you mean HAProxy? (https://github.com/EOSIO/eosio-webauthn-example-app#prerequisites)
HAProxy is just a suggestion, but you can use any proxy server or any other tool that allows HTTPS requests through and then update https://github.com/EOSIO/eosio-webauthn-example-app/blob/master/scripts/start.sh#L3 + https://github.com/EOSIO/eosio-webauthn-example-app/blob/master/scripts/stop.sh#L3 accordingly.
